
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author welcome
 */
public class OrderPage extends javax.swing.JFrame {

    /**
     * Creates new form OrderPage
     */
    public OrderPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelmag = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(java.awt.SystemColor.activeCaption);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 83, 32));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 250, 64, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Number Of Cans");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 190, 145, -1));

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 255));
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 114, 93, 32));

        jLabelmag.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelmag.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelmag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 299, 249, 31));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 76, 128, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Your Customer ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 36, -1, 22));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "cusid", "name", "address", "phoneno"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 414, 44));

        jButton3.setBackground(java.awt.SystemColor.activeCaption);
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 255));
        jButton3.setText("Place Order");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 336, 133, 37));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("..");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 220, 31));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("...");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 289, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(".");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 136, 32));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("...");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 182, 31));

        jButton4.setBackground(java.awt.SystemColor.activeCaption);
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 153, 255));
        jButton4.setText("Clear All");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 83, 32));

        jButton5.setBackground(java.awt.SystemColor.activeCaption);
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 153, 255));
        jButton5.setText("Check status of your order");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 200, 31));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Enter Order ID to check Status:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 194, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Crystall Waters");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SAVE WATER! LIVE BETTER!");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 210, 34));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Public\\Pictures\\Sample Pictures\\wallpaperflare.com_wallpaper.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new CustomerPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
        tblModel1.setRowCount(0);
        
      String cusid=jTextField1.getText();
      
      
      try{
      Class.forName("com.mysql.jdbc.Driver");
      Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/waters", "root", "root");
      PreparedStatement ps=c.prepareStatement("select*from customer where cusid=?");
      ps.setString(1, cusid);
     // Statement st=c.createStatement();
     // String sql="select*from customer ";
      
     // ResultSet rs=st.executeQuery(sql);
     
     ResultSet rs=ps.executeQuery();
      
      while(rs.next()){
          
          String cusid1=String.valueOf(rs.getInt("cusid"));
          //String cusid=rs.getString("cusid");
          String name=rs.getString("name");
          String address=rs.getString("address");
          String phnno=String.valueOf(rs.getInt("phnno"));
          
         String tb[]={cusid1,name,address,phnno} ;
      //   DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
         
         tblModel1.addRow(tb);
       
      }
        
      }catch(Exception e){
          System.out.print(e);
      } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        String s=(String) jComboBox1.getSelectedItem();
        int s1=Integer.parseInt(s);
        int s2=s1*20;
        String amt=String.valueOf(s2);
        jLabelmag.setText("Cost for "+s1+" 20Lit Water Cans is: "+amt);
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Random r=new Random();
        int r1=r.nextInt(10000);
       // int r1=9652;
        String status="ordered";
        String s=(String) jComboBox1.getSelectedItem();
        int s1=Integer.parseInt(s);
        int x1=s1*20;
        String s2=String.valueOf(x1);
        jLabel5.setText("Number of Cans you've ordered: "+s);
        jLabel6.setText("order details:");
        jLabel4.setText("Oder ID:"+r1);
        jLabel7.setText("Total amount :" +s2);
        String orderid=String.valueOf(r1);
        String cusid=jTextField1.getText();
        int o=Integer.parseInt(orderid);
        int c1=Integer.parseInt(cusid);
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/waters", "root", "root");
        PreparedStatement ps=c.prepareStatement("INSERT INTO order1(cusid,orderid,status,cans,amount) VALUES(?,?,?,?,?)");
        ps.setInt(1, c1);
        ps.setInt(2, o);
        ps.setString(3, status);
        ps.setInt(4, s1);
        ps.setInt(5, x1);
        int x=ps.executeUpdate();
        if(x>=1){
            JOptionPane.showMessageDialog(rootPane, "order placed successfully,please note your order id:"+orderid);
        }
        c.close();
        }catch(Exception e)
        {
            System.out.print(e);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jComboBox1.setSelectedIndex(0);
        jTextField1.setText("");
        jLabelmag.setText("");
        jLabel5.setText("");
        jLabel4.setText("");
        jLabel7.setText("");
        jLabel6.setText("");
        DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
        tblModel1.setRowCount(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String cusid=jTextField1.getText();
        String orderid=jTextField2.getText();
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/waters", "root", "root");
            PreparedStatement ps=c.prepareCall("select*from order1 where cusid=?");
            ps.setString(1, cusid);
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
                try{
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection c1=DriverManager.getConnection("jdbc:mysql://localhost:3306/waters", "root", "root");
                    PreparedStatement ps1=c1.prepareCall("select*from order1 where orderid=?");
                    ps1.setString(1, orderid);
                    ResultSet rs1=ps1.executeQuery();
                    if(rs1.next()){
                      String sts=rs1.getString(3);
                      String order="ordered";
                      String del="Deliverd";
                      String pro="proceed";
                      if(sts.equals(order))
                      {
                      JOptionPane.showMessageDialog(rootPane,"Your have Ordered! Our Team will Take your Order Soon!" );
                      jComboBox1.setSelectedIndex(0);
                      jTextField1.setText("");
                      jLabelmag.setText("");
                      jLabel5.setText("");
                      jLabel4.setText("");
                      jLabel7.setText("");
                      jLabel6.setText("");
                      jTextField2.setText("");
                     DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
                      tblModel1.setRowCount(0);
                      }
                      if(sts.equals(pro)){
                          JOptionPane.showMessageDialog(rootPane,"Your Order has been Taken! Our Team will Deliver Soon!" );
                          jComboBox1.setSelectedIndex(0);
                          jTextField1.setText("");
                          jLabelmag.setText("");
                          jLabel5.setText("");
                          jLabel4.setText("");
                          jLabel7.setText("");
                          jLabel6.setText("");
                          jTextField2.setText("");
                          DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
                          tblModel1.setRowCount(0);
                      }
                      if(sts.equals(del)){
                          JOptionPane.showMessageDialog(rootPane,"Your Order has been Deliverd!" );
                          jComboBox1.setSelectedIndex(0);
                          jTextField1.setText("");
                          jLabelmag.setText("");
                          jLabel5.setText("");
                          jLabel4.setText("");
                          jLabel7.setText("");
                          jLabel6.setText("");
                          jTextField2.setText("");
                          DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
                          tblModel1.setRowCount(0);
                      }
                          
                      
                    }else{
                        JOptionPane.showMessageDialog(rootPane,"Check with your orderid" );
                        jComboBox1.setSelectedIndex(0);
                        jTextField1.setText("");
                        jLabelmag.setText("");
                        jLabel5.setText("");
                        jLabel4.setText("");
                        jLabel7.setText("");
                        jLabel6.setText("");
                        jTextField2.setText("");
                        DefaultTableModel tblModel1=(DefaultTableModel)jTable1.getModel();
                        tblModel1.setRowCount(0);
                    }
                     }catch(Exception e){
                    System.out.print(e);
                }
            }
            
         }catch(Exception e){
             System.out.print(e);
         } 
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelmag;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
